{% set name = "xproperty" %}
{% set version = "0.10.3" %}
{% set sha256 = "da37de44ba6b58ea25f58d29cfaefd163514f403159dad16009f76777eda3a07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xproperty/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xtl >=0.6.11,<0.7
  run:
    - xtl >=0.6.11,<0.7

test:
  commands:
    - test -d ${PREFIX}/include/xproperty  # [unix]
    - test -f ${PREFIX}/include/xproperty/xproperty.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xproperty/xpropertyConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xproperty/xpropertyConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xproperty/xpropertyTargets.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xproperty\xproperty.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xproperty\xpropertyConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xproperty\xpropertyConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xproperty\xpropertyTargets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xproperty
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ properties and observer pattern
  description: Leveraging C++ template and preprocessor metaprogramming techniques
  doc_url: http://xproperty.readthedocs.io
  dev_url: https://github.com/QuantStack/xproperty

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
