{% set name = "xproperty" %}
{% set version = "0.5.0" %}
{% set sha256 = "638a2e155f6185b27ace31186ec7405d052d3c5e95932de234b2e618057d4921" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xproperty/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
  run:
    - xtl >=0.3.4,<0.4

test:
  commands:
    - test -d ${PREFIX}/include/xproperty  # [unix]
    - test -f ${PREFIX}/include/xproperty/xproperty.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xproperty/xpropertyConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xproperty/xpropertyConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xproperty\xproperty.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xpropertyConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xpropertyConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xproperty
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ properties and obeserver pattern'
  description: 'Leveraging C++ template and preprocessor metaprogramming techniques'
  doc_url: http://xproperty.readthedocs.io
  dev_url: https://github.com/QuantStack/xproperty

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
