context:
  version: "0.12.1"
  build_number: 0

package:
  name: xproperty
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xproperty/archive/${{ version }}.tar.gz
  sha256: e8fd89e8b4bfd1631189654156dc9da4f668e011f8ccf8bc3fdd723479922b18

build:
  number: ${{ build_number }}

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - nlohmann_json
    - nlohmann_json-abi

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}include/xproperty/xproperty.hpp
          - ${{ "Library/" if win }}lib/cmake/xproperty/xpropertyConfig.cmake
          - ${{ "Library/" if win }}lib/cmake/xproperty/xpropertyConfigVersion.cmake
          - ${{ "Library/" if win }}lib/cmake/xproperty/xpropertyTargets.cmake

about:
  homepage: https://xproperty.readthedocs.io
  repository: https://xproperty.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ properties and observer pattern
  description: Leveraging C++ template and preprocessor metaprogramming techniques
  documentation: https://xproperty.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
