# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zTPXZovImBmiZmYI6vmLGF9TK8Wv9HhtyUsqnAbS/H1J7PZedyYO3+8pjp2vrFcO3iPRqAa7NvVaYLAgfkj8OVBaUNt+hs3pMElsV28TkGYBFVZNY+HdNJa59SlClVJ7KH+jHiW2m2eSF8O/rYMTAY15JqxhCxb2THpfwJMBp2B2C+l+AY5g5t6Naz/V+ARkiu677PNovg06mFr4hJrddvVGEumYmMnsotq9ohVh66T17XqE1PrWDLfxhcZvJHmF5dzJrRdTrmWG5bqkPnQgKXudj3INHp/Chxo4/yDTG/JM98WgYZLTKu2/Dc1dQVEY9jv/JUYiBgDhc8/CztIwGp04RltCwfsceuHM9Jm2t1UXhMZ6Q9aoyZ4m1SyhqqsroQLGLMAyo556j8hLnWg57EpU0R4FAnAogDrj8TvuoIIxJa8Ftg28QI3GfC1x58SM6byv/+sh3lNNr7Uy+u6yqAXbaoVdOxccNO4/IuDC6sSlYmb8nvh5MHIb+oWjFFE0Wl5xqEmpzlgV/UdsIw6lpM4Dt+5BNPwnUeqdeLBRTF8Vm33kCwTOaQtdIQGK0heUpLVqnZI1IKzCK1gljq0cgVJEKmzyGNoWOReEYXq1ULSlGZ/6sp0wFLsuXQKJ+B4gokU8Qw+s1G/Jw54Xq4cPxr71sxvTYEG0KEqglCSRsio="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
