# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SeDKYfDZ9pricJWkWiZLYpXqUPEptM1zDUEa9yEI8xVWuhTygGoMvVCwIr6C/pbHcChTRHB1xf0w3HdEV+HPw/2Y03/KOOj2rx8Ai9yn5rCHmAZSgK7//Iq6DJ53C96Pj0Tstrbsa/0w5Otd+9+lLXb9Sewh5E4mtn9+pgHePjZuqnTMmIQUf+a0nbIxr4qOkRiObk4SDToqW3IvcZrWuXJKVnhv4nmr+LPPTUYVD3OuMX7O4RAeqot3ajyjfK42281eHQjS9kXD8yPNi2RUoAuasP1/DdrdS2FYdzVPTrt+FBSrbEmcvl+bl77kkaBHdLN5x4TTMONGSQk1K7mOsqQMgot7I62BfcO5SBnzBMFnwdeCV9LAK9eYRj3nD3fYS1Gbkq1paYAVDwZiD9N4qJsMI5okdygUAwfFFUkP8LcycSBm4LN7yiCXbCejcndBXXb5sGFSRXt+RpCHfzXG0IYuXsNPGiSk37c1sjHRRL9WaNLrW5hWC44G0U2aTWH/TjzMcyrYDeYgoLdXTo+A7FGXfGiBv5JZeS8J8v7zOug/Sh0XEPjAS5ETa4yUqjSkIV2E85FWfd1/vUCwR7YYo6l2RBRNbhT7G5FgBmvtVvMRabnjb+v7qZxKlW5sOeP87RsmuyF24fXVp+xLgYvuShEfcWqetkL4ftIuTwDUlDM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
