travis:
  secure:
    BINSTAR_TOKEN: SeDKYfDZ9pricJWkWiZLYpXqUPEptM1zDUEa9yEI8xVWuhTygGoMvVCwIr6C/pbHcChTRHB1xf0w3HdEV+HPw/2Y03/KOOj2rx8Ai9yn5rCHmAZSgK7//Iq6DJ53C96Pj0Tstrbsa/0w5Otd+9+lLXb9Sewh5E4mtn9+pgHePjZuqnTMmIQUf+a0nbIxr4qOkRiObk4SDToqW3IvcZrWuXJKVnhv4nmr+LPPTUYVD3OuMX7O4RAeqot3ajyjfK42281eHQjS9kXD8yPNi2RUoAuasP1/DdrdS2FYdzVPTrt+FBSrbEmcvl+bl77kkaBHdLN5x4TTMONGSQk1K7mOsqQMgot7I62BfcO5SBnzBMFnwdeCV9LAK9eYRj3nD3fYS1Gbkq1paYAVDwZiD9N4qJsMI5okdygUAwfFFUkP8LcycSBm4LN7yiCXbCejcndBXXb5sGFSRXt+RpCHfzXG0IYuXsNPGiSk37c1sjHRRL9WaNLrW5hWC44G0U2aTWH/TjzMcyrYDeYgoLdXTo+A7FGXfGiBv5JZeS8J8v7zOug/Sh0XEPjAS5ETa4yUqjSkIV2E85FWfd1/vUCwR7YYo6l2RBRNbhT7G5FgBmvtVvMRabnjb+v7qZxKlW5sOeP87RsmuyF24fXVp+xLgYvuShEfcWqetkL4ftIuTwDUlDM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
