travis:
  secure:
    BINSTAR_TOKEN: t7aV5Pts7IAr6i89ktwGbbeCce3rI3SX6a20lIcYrseP6oU68NBX7Kib9PBe9790W56fiMeuMjI0Zg4pTM3ww6Kffs6/LfofZSaipnXmNyaKHnOC9YxT7Tavr7UE9xiaUIime+wAzJVDm9yiiQbzyw6Xuaj1/BzqPgLM/yITiOEWExIO+8MvrLRMUSv/FStXM83kWyW7Z2xi0oEtEsEmWwl6klJYgfaLCMSSa1taMG1Po3GOb5yvYY4TgTapZt9PXfoI80NKxNfE6W5i3eH1Z/gubMpbhMn2lFGs5Fw7mRIPetsQnl8tv2Uvw2z+GT/nSXaET8TSC8PBqPYghM7bkisg3awyuyv24OWARbB6UerT/UUuxVT2B252GBNyyABL5j5ENWWpdOCUXJEU5FQojzMXwa4yLcYV2flIApyEqoiNY0QHaxHHceaLLSoSFnz4aUywbu9hD8oJpO+8Z+tGsvwsWW7y70mCLT+0jhf71hk7e3cwIDKNfjqeS9zV8AwCCH9yqtcst54IcO/FDLtbsJRbYRD1GeFltNOnEEBW5W6IRJ7LiGRxK0I1ODgeBPvk5wcWQP2Z24IMxMbQHowL8FVeSQdVfH2ivY0kkTdI8+pzztQfeK1YnhtDkJ0Ta+rJRLirUqo4+TtvNgkwlzGnBzlUvQMeyhGYFGA7Y469St0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
