appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LDETu2JgmqI6zFxP0zk0Sx41LlqdUSAlPIcMFdxC1ky1OJ7PMeJ0uYI6IxkCUwl4M/ZHr/S+pPE+L3sw3XbHgZVUU8EdL5HCZjbzxgpqlOc6y237ZaNN0WMz3Eb5d9ia+Fk3Lw/bK0psq2lcb4cMlytJc6H9Y1DFef1gVY5cnnYxEcAC5ZIteUozWfHCp/+Xpm2rydNrOsgvQNv6eY8bZl9LI8iN1B7305prS9tVeI9pd1UCAm/dZ1ZWhIFco4TKHDc1lHcyjcoykUNgL9XAquTJjIkB2KmCAdXdNd7SUNK3ZDJLd4fzo0Q+yDSbSms36GISP71AmkA7vCK4FQ6Vr80/jsPrfUz6mchmNQi40Oy5tBY6KXZQhU6EOYbw1MQjWgZVnKlRkVWm7E7+FgmdP0axp6/ZxUg1tHIPmag+ncjuqmFDAXU1s/5fiS88W9SUnNuPHZ/aFNgHZOaP7/W5kY5ypSuXOeMVtCipEpe6xQIC+DO1tCbBT1l3g/GxvMUgAWtDOEPZ/3/wZzgwC1uX8+xIBRicae6HprfapbcEexM+BhyAucpjofCtFgknyG2eNzJebh7OWubXPkonU6gfDgitinwp1FHBhSCO+IpBJWoEeaQ0IHZ+Gwk3t2G8OFcf2SL+KM/Jpk8msKqF6msKIRHEajVTL05543EeBsM4Ig4=}
provider:
  win: azure
