travis:
  secure:
    BINSTAR_TOKEN: kv5hUOeDEQaKh33QpE3bJaikB9Ek4Lt/HKzGh2tX6TJNxEqn44H0ILAG7g+fHfaPvJCJEnLqW8Jx9SpEbXnuxW/A9KqOBwrgpuPMD4fzMpvkXYvyLzEGKMK/kOvq6tcpDQWpfUZu3AHOIRgH6nmg7oFRWXHKDmHLz5rmVrRh0rYyBjezo4/8iDIwmx696a/PxFnjWy0ih6e+n/E8IlEHneE9UI+vtJQXLZNEZPLJcgWzkUM/2HP7jsH1UZL3GN0XbKnzuR6sQL6CizZJ7iRuVXtgxOStLcpykM3WMOkFphUG2bfa5glV5h7b9h2ZuzH+z6/C9VIdyAhVOdp2GbhH6fNWSEwG5QS6xbaPsEOSB5KBuAnGM4q1PKx0cTwc6SZg8C6JCPsFAMDhD5CbVZl54gJ6ksEgQ3yt6VLmpph/5delnFUEr4zv79KKaHiN4XJhyQDikmAIzmfVVGU0q3aO8QmknCM1Cug9Bh2nyHXWHN0aXTzCeO2K9xuzrFWXIso2m6illscldNtOm/OAXT9p640JgeoyFa0knGLTt9z+P/0oSNQl0WQhHSLTm/XdtCv7Z/xXatILfE0ycbjE3hC4V6EBLDsye74O+t13iBTV5gCb4quRYOrhigJq+SMIfVDVEbAo9BpMSE1hq3erH544kIGhMKfKahAM+eKyWE6KbA8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
