travis:
  secure:
    BINSTAR_TOKEN: ppUNr9u2cB8IrQjuaVHEwENZej1mGBNB3J2FLwNT9/fBP/06EzKeZZAK2oB7hNkwtaF7hhz5pMADesffc6VGWU7Ss+sYmKpnaQh5hj3v+Y9sNKg1v1nqaSMJ4G0i5ahpIg19lcJGDsnYmTaTtidboSiSLcGjEoa3xbV00Z2tfD+jAUjYI664G3vYC/i+HeM139Vv4DrMwWInODIIcqFsHgZF5S9/pAsWV7UG9F9ViaR0Fl8AdhK7wwSJhuwUe1WdabOJMf+4uZbsXPO6PZgqCl3JO3GtMCWZoucLM2qISjl/Aaex9DJQR1cGPzCHntRdN5lj9ag6gYai0UN1AjeNSg8Ba54heweE51uT/4NFAyNxAeCXqvlkaMw2ITGv/EI1mRIq6GjVxmoSkKKP7fHe6ETeVudBpdN6ylX7jAYGmYTAFMDdj+KGEyprvOlml4XKVwr4V0XmJ3aSaD0sM65Icbtvqij9U7jw/XDEpplT6llGOU7PwyBM7eIRgsHRJLdA1ba/HqmmdDCMOCrU9pyh1J/l1kD0WYDp5ulV6PqG0xXzDGfA1bzZu5ukxMthnJJO9zWcoAoXy1bL3kIliaVV0Nu9aiCZxZpExEN00gy8STefX0dtAdVQNBvBfBb3zV1nj1uKDPaoEWzaJi5NY3Mbi7mv0G10BBQiQsnpwnRiKEg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
