travis:
  secure:
    BINSTAR_TOKEN: yc5clH4n27C/lFSlW3fsb4Z2EG77z1OL1d78+3gISmRa9WW6O1aEEtJWmMDVDDIEH1UvPQssl8rgVQc9ixO9e7xD7kdcMJOa/DhLkYvj8GIVuO0oAF71Tyebrsy0Px6OhtlveqWDOUtCT85taJf2QM6pnsKddgqhFde2viCM4KSxWvRL/VDtv45DtTbNGdS2ru9gIOoS25pgmqsbixWAlqyOWKNewmmRswCUj+BE/1XzIqYPKGooe+3ykPvcsCryFRhHWmSeDJ2lFuM71doz6RoKhpk/76EJy3+osJGbQL2GaR6QNyGJPHEoxuYZQy3L5yWkIx1OGGzpL7F7Ns16+a1S6+F0UyzVCHcfbHWWIXhCxoXl53BML5EvqQwtLhT7vZTT6As5YSfM0gcvkYHfI9B4g7yZce9fgRUvr38M49jE1vs1TvhhFFBvMskGN/tHI4di1NWpAsrZg/ThmxK2BrmS1/awzoYh6WIDUBIHlOd8Mf31JPPE2yiZLtt8pTh4fZG0e5zeTZRiZk69Gd5sDtLkgFHvd4Rey1td4Ja97Cuuy5bKlJFxpvgoT9XL9JSEOL0O3sxIGs2Bjoy08WpfyXnnGF5LhEMMhZc7/oqxBLco6lX5wjhw4Mxtx8tvYQj3wOeF/fYxJC9eLPkKBzUBZDn52oiEm1wcJrukHA6gngA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
