travis:
  secure:
    BINSTAR_TOKEN: KthmkXgacGem2qWva3OiB8yYud0weGc86u2JigWmJADdJsK6trqy5WaCGkUlu+pIigG3zKgPB/obQ48YhX9AzUbSGlbP6lCSZM45O99KQnMLBn8K7el9b/tyl8tt6yU/lefw20tR7YlZ7eXCvAoP2IM9lc7TusPFBGvSRagcdXN9FvvzuDJxheJxT0sSdv+H9y+w5PfytQsWZoKFsY7JfRaT2Ooz2IsXnvUEpMYwav2RXw5npWrUtU9IT0Qcgt7S48eIG2wOQhb/wLj1d7vwncxM42o73pt3lIYn/aCJsQ+2sdROsZ0Jkn+ZTviMEqeo9gqvQYepCt7gcvLw0d1OXVB5dG5JCy9id2UAqs/dkVDwJGgPSwmMTAmEmkvKcb3drJ5wtC4RLHVVp30uBQCTXsugDq77+KC6UigsDVrJzQCsOqeYswwFPbHTyZxP5FsscxZO1Gee45Y49ZpjPoW89G/5QcQtSeNSrM7E2RmlxlN3NsMY2LG5pLQhRvlhRzi7sh9ZTMpGkCzFAYmTDrsfiRsnU2/g5lrIx+It7vmycXyzteyfOGlJs0mH2stvSrBqh/2UYdZjbirnfFzvLAKLayn+h88YnSwxqnWpc+OCDDv+ZQWds12/Qg91sUDsKJIFVRLAUYG2MzXAoHD9v4Ni3CR68tk0j0wdoAbVBtXuCEA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
