travis:
  secure:
    BINSTAR_TOKEN: x4uYdQ5wHeLWeY/bTBivcMuKcFj3uJZXW25lKesJDLb8FKUefbSs1q1mF6kjDL5r4udlGgy9dCBrKCMVWpI4SeaJZmDrBuFyBtiq+gynKeKJfOBb/eZT1hEdt5LtoorcxqMcxQMtXSgEVnJTsv6+cg0ZSRKRYhLmy7IOXNWiQUgJtIeOgHDqcwoRkmxeOL1j6IsDaCRcbPrzJhcZYc7h9NebYWJFhtPN+P0bJPsUAaz7+KPxmvpNL1GHOd9tWl0fX+qc3A+KUxEwG893GlAADiJDU1kg/vTu12+bJ6f4ZO70FsYdJk+7szMSGFq+oO6Rvis2V8LbCRLpjIKgAYpKPZwVa+sNUaQG7n2jOetcla1aJe0heGrY3JG1z1o1uFqonVZkgsw1J8abP5ttczWWOFn8mYaoTxV+zdfQ6M1pml9KcBm3Q9oHtUHp2GVE6E1nz97SOmIWTDYYVThXzoe2XQ8Yge8yIeEWxkbBxwnWz6vym+Za2AyyOQY1Pr5mXCZ3bdTq0rjmIU3jHyziPaiR4KOJC5ATkO+WUOGVHRJQnIJy+drJ7Z6smy9iLd6u62SE7UsJoFSEc/rveL93mjIeqZiVVbs6kaNZO3MIJD+wFC3tF/BbhexjjoB8FCjod943xN2DpPnLOBDLKa4VPRGbX9emw5Aa8aamqmzqS5Popq8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
