travis:
  secure:
    BINSTAR_TOKEN: w2SFrEjgxpLPR+7QAtb2qjaSEkcHDwhQLoLKT7UQco1J2cW07d5DlT2JpEG4CyS+q4s4UjZKn0PaClnMvwjfSdDO8/NKd25U1ykP1yN8KLaN7Ku2V/zywvOliEJx+Z26w902oOnL1nhsjq46OkGLoyIrNbinC5jNsYCzFEyVa2QYFPE/VB4OqDOtDFVDoe8BFKgxN/T5pkm72VOIfaYNBIJaWd51TO/2a8lHlIEsbI6IP8EttCUXocBx5xzzl3aRzVuCoigicSr3i25fDnCJ6auAvAwEN/qkLpu41IEJsKL3pqjNWt+k0g/fCEMWyliCzHKgJQVVO3Zwdffrp2uI63j2ohRon+llFjVbsp62WtfFqcR8PEgn5mTPHRuf3Nof9GvqY/m4QN444E4YqbXbr9BEc1WMWOOY1MuiJbIKSH65CI9Kpua532Btyehiex/rmUUAyHP4+p47KPbHNdVgZLPG0h5I+H/8RExDYztsHifqEad2CigVYT/xBIKaIEk/d1ccJr60aS/4qmGrCMTEywYckIojkSkScOUTnvLLgFitgwm9GfBZ+E/k8Q9rZXjzHHMqEPaHLXSM06w7yez5DkJZbZEbCftuPUN0FG7KdO9hn60taI7+j10hjwUZdsSpsYrzpSzDq2a5EUG4ZM9AjPTKHMivnb33T552uEMGuGg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
