travis:
  secure:
    BINSTAR_TOKEN: Vb1/iM178Dedj/RHIC9p9RNQwoYy4Z5GINj7ROERozGavq0FC0MMJmqIBdh0dBagy6qcetyz9El4pOVjtabCJbf5S7sxetSzaOE0/4bhbZlz9XdKCcHOoh8u1440sRA9Y9Mz71F2svST/adVSqsNfjMH4YjZBVIAVBCJp6L17TWXSWE5keOFHNYJJcT7EfZUZ+5zImvxpT68lzCWyKG8QPc/dBp8o8O7emT91ZYeqYlnZ7ODCWU0xiB3fplqRRFNJzt88waqjuI813/aEh/L8QuIkNBNRLtaoFjueS25cJIVnzO4q2GcXAHno673aLxjbJvZ8fhTPj9U7T+pefaugkjvd0KNSJuGVTROncF3TpjgCOo9eqbApXGiDxQzBNnSF1SA7MXhyt8mEu+CCJQOB4iYGRtrNpjc+xssyWwUEtXdDf8FvUfosZ+KeMdM87cVdxU386p7TtX6S6/qLjKHTKgGaAZF7IxmBGCaNv/t7GiMcti2gsCiXBOk7rfY63i0+dPjh45NoAHA1hm7CYgkpb4X5b0OOEgf1N2pmnYLZXlwhrztmM1/EpXwoO1QSsiCN4SBeF/zuzvbS+ocOC54pno0sTgMx+QTwuoU62qn2bWxvc4iVLuTvC8aece7ve6tk5vcw9AsICuYknBf0oex7tMyfpdmpzdXx/6hPcvpZaY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
