travis:
  secure:
    BINSTAR_TOKEN: p8cZQ0tCXLX/B6H15xGyPUDUjn7I8JhORtaK0lt8ApbQC7JZKp7Kn9QxvXVn/W0+DWfSNuo6FLQXHtnQQpff3+hL6SByt4HPKT2U1dyVx+CmOcWYN86CYSF7uHZSuoszECKoCt/k/y5iKQFd2t2gJrO2qhLrOpU+WLWDzsmlg8ArtBO4rZkGAf3eucev0+bhlv8om6y+2N/5jIF7P0m+o23sQ5BsfTUFl1WTNUS5jwcdH8MVJeI5IbsacYIoq2PvK2pTv1e+zzr6UZ4vwFevLajW0sibXyCGy47SOyXrWiAwLldISFKnoAMM2ePMqpYM4kr2bGbHlnWPRwpUP17+Cc8CB4c5Ho82KEuhwMunZXaPcj1bKtEvCcrEj3pR6apf5WgkQEyspuWs/kdYKIazQSF135UFgY4ahlAv2Hb7wNomzk3mEW58VawXs+U2baafqmQmHvhjxnNuZ3WAu1BOlu/u4xzdpeLQbmQmuCQE8thSBUYcKfagiA08a24dnIldRpm+gDNeA6irSlJnoB77JQWs19VOKqshpW/Wqi/NTXSo7MXb0w3Tlf6wdaTP7ZrL58aEt6gIN4vUpQPd6iAPSXQ+SECRbBpEI5/KVd8rOP153a4Pt5PLlXaJXwzPY1HYp8VNo2GUhb7oOJN++d2k1CtzmVOUHjd2lwpnPX8MEL4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
