travis:
  secure:
    BINSTAR_TOKEN: zTPXZovImBmiZmYI6vmLGF9TK8Wv9HhtyUsqnAbS/H1J7PZedyYO3+8pjp2vrFcO3iPRqAa7NvVaYLAgfkj8OVBaUNt+hs3pMElsV28TkGYBFVZNY+HdNJa59SlClVJ7KH+jHiW2m2eSF8O/rYMTAY15JqxhCxb2THpfwJMBp2B2C+l+AY5g5t6Naz/V+ARkiu677PNovg06mFr4hJrddvVGEumYmMnsotq9ohVh66T17XqE1PrWDLfxhcZvJHmF5dzJrRdTrmWG5bqkPnQgKXudj3INHp/Chxo4/yDTG/JM98WgYZLTKu2/Dc1dQVEY9jv/JUYiBgDhc8/CztIwGp04RltCwfsceuHM9Jm2t1UXhMZ6Q9aoyZ4m1SyhqqsroQLGLMAyo556j8hLnWg57EpU0R4FAnAogDrj8TvuoIIxJa8Ftg28QI3GfC1x58SM6byv/+sh3lNNr7Uy+u6yqAXbaoVdOxccNO4/IuDC6sSlYmb8nvh5MHIb+oWjFFE0Wl5xqEmpzlgV/UdsIw6lpM4Dt+5BNPwnUeqdeLBRTF8Vm33kCwTOaQtdIQGK0heUpLVqnZI1IKzCK1gljq0cgVJEKmzyGNoWOReEYXq1ULSlGZ/6sp0wFLsuXQKJ+B4gokU8Qw+s1G/Jw54Xq4cPxr71sxvTYEG0KEqglCSRsio=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
